### ISSUE TITLE
Can only scroll backwards in idmode number for NA exclusive cards

### ISSUE THREAD

**Issue by ethannp** [TsubakiBotPad/padbot-cogs#146]
go into ^idmode number
try ^idna 4953 (or just ^id 4953)
you can only scroll backwards (left) through the ids and not right

**Comment by RheingoldRiver** [comment]
duplicate of #123

**Comment by RheingoldRiver** [comment]
wait I read this too fast sorry

**Comment by RheingoldRiver** [comment]
closed by #147
